[package]
name = "editor"
version = "0.1.0"
edition = "2021"
build = "build.rs"

[dependencies]
slint = "1.10.0"
rfd = "0.12.0"
reqwest = { version = "0.12", features = ["blocking", "json"] }
serde = "1.0.219"
serde_json = "1.0.140"
dirs = "6.0.0"

[build-dependencies]
slint-build = "1.10.0"
